#!/bin/sh
SPELL_FILE="$(git rev-parse --show-toplevel)/stow/vim/.vim/spell/en.utf-8.add" \
            vim -i NONE -U NONE -V1 -nNesc \
            'execute ":mkspell! " . fnameescape($SPELL_FILE) | echo "" | qall!'
