#!/usr/bin/env bash
#
# Install Ansible and run Ansible playbook.
# Use pyenv exec instead of pyenv activate due to pyenv/pyenv-virtualenv#372.

set -euo pipefail

readonly THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly PY_VERSION="3.9.0"
export PYENV_VERSION="dotfiles-${PY_VERSION}"

is_macos() {
  [[ "$OSTYPE" =~ ^darwin ]] || return 1
}

is_ubuntu() {
  [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]] || return 1
}

is_debian() {
  [[ "$(cat /etc/issue 2> /dev/null)" =~ Debian ]] || return 1
}

install_homebrew() {
  if ! type -p brew >/dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
}

# Installs pyenv if not installed.
# Globals:
#  THIS_SCRIPT
# Arguments:
#  None
install_pyenv() {
  # Ensure pyenv is in PATH if it exists
  export PATH="${HOME}/.pyenv/bin:${PATH}"

  if ! type -p pyenv >/dev/null; then
    curl https://pyenv.run | bash

    # Install recommended dependencies
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    if is_macos; then
      brew install openssl readline sqlite3 xz zlib
    elif is_ubuntu || is_debian; then
      sudo apt-get update
      sudo apt-get install --yes --no-install-recommends \
        make \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        wget \
        curl \
        llvm \
        libncurses5-dev \
        xz-utils \
        tk-dev \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev
    fi

    set +u
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    set -u
  fi
}

# Run command using correct Python interpreter
# Arguments
#   command
#   [args...]
run_python() {
  pyenv exec "$@"
}

install_python() {
  if ! pyenv version; then
    pyenv install "${PY_VERSION}" --skip-existing
    pyenv rehash
    pyenv virtualenv "${PY_VERSION}" "${PYENV_VERSION}"
  fi

  run_python python -m pip install --upgrade pip
  run_python python -m pip install --upgrade setuptools wheel
}

install_ansible() {
  run_python python -m pip install --requirement "${THIS_DIR}/requirements.txt"
  run_python activate-global-python-argcomplete --user
  run_python ansible-galaxy install macstadium.xcode
}

main() {
  is_macos && install_homebrew
  install_pyenv
  install_python
  install_ansible

  declare -a args
  args=("${THIS_DIR}/ansible/playbook.yml" --inventory "${THIS_DIR}/ansible/hosts")
  is_macos && args+=(--ask-become-pass)
  run_python ansible-playbook "${args[@]}"
}

main "$@"
