#!/usr/bin/env bash
#
# Install Ansible and run Ansible playbook.

set -euo pipefail

readonly THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if ! type -p uv >/dev/null; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

export DOTFILES="${THIS_DIR}"
uv run --directory src/dotfiles dotfiles
