#!/usr/bin/env bash
#
# Bob Gardner's Install Script

download_git_helpers() {
  wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash .git-completion.bash
  wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh .git-prompt.sh
  printf "Add `source ~/.git-completion.bash` and `source ~/.git-prompt.sh`" \
    "to your .bash_profile"
}

download_vim_helpers() {
  # Install pathogen.
  mkdir -p .vim/autoload .vim/bundle
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

  cd .vim/bundle
  # Install GitGutter.
  git clone git://github.com/airblade/vim-gitgutter.git

  # Install NerdCommenter.
  git clone https://github.com/scrooloose/nerdcommenter.git

  printf "Download desert256 from %s into ~/.vim/colors/ directory\n" \
       "http://www.vim.org/scripts/script.php?script_id=1243"

  cd ../..
}

cd ~

echo "Do you wish to download git-completion and git-prompt?"
select yn in "Yes" "No"; do
  case $yn in
    Yes ) download_git_helpers; break;;
    No ) break;;
  esac
done

echo "Do you wish to download your vim plugins?"
select yn in "Yes" "No"; do
  case $yn in
    Yes ) download_vim_helpers; break;;
    No ) break;;
  esac
done

echo "Do you wish to install all symlinks to your home directory?"
select yn in "Yes" "No"; do
  case $yn in
    Yes ) ./symlink.sh;;
    No ) break;;
  esac
done

